#!/usr/bin/env bash

git clone https://github.com/ggml-org/whisper.cpp
cd whisper.cpp
source /opt/intel/oneapi/setvars.sh
cmake -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER=icpx \
  -DCMAKE_C_COMPILER=icx \
  -DGGML_BLAS=1 \
  -DGGML_SYCL_F16=ON \
  -DGGML_SYCL=ON
cmake --build build -j --target whisper
cd ..

CC=icx CXX=icpx go install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/whisper.cpp/build/ggml/src/ggml-sycl:$PWD/whisper.cpp/build/ggml/src:$PWD/whisper.cpp/build/src:$PWD/whisper.cpp/build/ggml/src/ggml-blas
whispy ~/.cache/whisper/ggml-large-v3-turbo.bin
