#!/usr/bin/env bash

set -eo pipefail
shopt -s dotglob nullglob
trap 'echo "${0} line ${LINENO} Status: ${?}"' ERR

git clone https://github.com/ggml-org/whisper.cpp || echo "Using existing checkout."
cd whisper.cpp
cmake -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DGGML_VULKAN=1 \
  -DGGML_NATIVE=ON
cmake --build build -j --target whisper parakeet
cd ..

go install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/whisper.cpp/build/bin
echo $LD_LIBRARY_PATH
whispy -print-text -keep-audio
