#!/usr/bin/env bash

set -eo pipefail
shopt -s dotglob nullglob
trap 'echo "${0} line ${LINENO} Status: ${?}"' ERR

git clone https://github.com/ggml-org/whisper.cpp || echo "Using existing checkout."
cd whisper.cpp
source /opt/intel/oneapi/setvars.sh
cmake -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER=icpx \
  -DCMAKE_C_COMPILER=icx \
  -DGGML_BLAS=1 \
  -DGGML_BLAS_VENDOR=Intel10_64ilp \
  -DGGML_NATIVE=ON \
  -DGGML_SYCL=ON
cmake --build build -j --target whisper
cd ..

CC=icx CXX=icpx go install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/whisper.cpp/build/ggml/src/ggml-sycl:$PWD/whisper.cpp/build/ggml/src:$PWD/whisper.cpp/build/src:$PWD/whisper.cpp/build/ggml/src/ggml-blas
# echo $LD_LIBRARY_PATH
# whispy ~/.cache/whisper/ggml-large-v3-turbo.bin
# whispy ~/.cache/whisper/ggml-medium.en-q5_0.bin
whispy ~/.cache/whisper/ggml-small.en-q5_1.bin
